niaid/image_portal_workflows

test/test_brt.py, test/test_dm.py, test/test_sem.py
Fixed merge conflicts. There might be some Config executable paths defined that aren't used.
=> Readded just the test classes to use shutil.which(), not util.Config.

.coveragerc, docs/source/development.rst, requirements.txt
=> Added pytest coverage including documentation

.pre-commit-config.yaml, coverage.svg, pytest_coverage.sh, requirements.txt
The `pytest_coverage.sh` script runs all tests, prints a coverage report and updates the `coverage.svg` badge for display on the main page. The image must then be committed to git for it to take effect.
=> Added script to manually run test coverage.

em_workflows/brt/flow.py, em_workflows/dm_conversion/flow.py, em_workflows/file_path.py, em_workflows/sem_tomo/flow.py, em_workflows/utils/utils.py, test/test_brt.py, test/test_dm.py
It can be useful to leave workdirs in place, not automatically delete them upon completion of run.
This adds a new top level Param to do this. 
Also surfaces/refactors out workdir rm in brt flow, no longer implicit.
Also adds test.
=> Adding debug option to prevent removal of workdirs, closes #194

test/input_files/dm_inputs/Projects/Lab/PI/SARsCoV2_1.mrc
Single file added - it should be handled by Git LFS. It's "only" 33 MB - small for an MRC.
=> Adding MRC file for test coverage.

em_workflows/file_path.py
I noticed that FilePath wasn't printing out in testing and fixed this typo. I made it a separate PR in case it caused unexpected issues. All tests passed.
=> Fixed typo in __str__ method

docs/source/metadata.yml
The value ordering was not consistent with the other examples.
=> Correct legacy example for metadata

docs/source/ImageSet.yaml, docs/source/PipelineCallback.yaml, docs/source/demo_callback.json, em_workflows/file_path.py, em_workflows/utils/utils.py
move title into imageSet, create imageSet obj
Keep file level title for now, add imageSet element name
=> conform to new callback format

.github/pull_request_template.md
=> PR request template

em_workflows/czi/constants.py, em_workflows/czi/flow.py, em_workflows/file_path.py, em_workflows/utils/utils.py, test/test_czi.py
Addresses - https://github.com/niaid/image_portal_workflows/discussions/227
* Adds workflow to convert `czi` image data
* Workflow now uses `pytools.HedwigZarrImage` object for zarr manipulation
* Breaking Change - the callback data structure ( the new structure has been merged https://github.com/niaid/image_portal_workflows/pull/274 and it will be reflected on this workflow callback)
=> Adding new IF czi workflow

.coveragerc, .github/workflows/coverage.yml, .github/workflows/main.yml, pytest.ini
* Add pytest coverage detail comments into the PR comment.
=> Add coverage comment workflow action

em_workflows/brt/flow.py, em_workflows/config.py, em_workflows/czi/flow.py, em_workflows/dm_conversion/flow.py, em_workflows/enums.py, em_workflows/file_path.py, em_workflows/lrg_2d_rgb/flow.py, em_workflows/sem_tomo/flow.py, em_workflows/utils/neuroglancer.py, em_workflows/utils/utils.py, test/conftest.py, test/test_brt.py, test/test_czi.py, test/test_dm.py, test/test_lrg_2d.py, test/test_sem.py, test/test_utils.py
Addresses
- https://github.com/niaid/hedwig-comm-specs/issues/4#issuecomment-1701512859
- https://github.com/niaid/image_portal_workflows/issues/295
- https://github.com/niaid/image_portal_workflows/issues/296
* Uses a mapper over `env`
* FilePath initialization requires `share_name` argument (previously not required)
* Config. `proj_dir` and `assets_dir` requires `share_name` argument (previously relied on env)
=> Add file_share param into workflows

docs/source/AssetType.yaml, em_workflows/brt/flow.py, em_workflows/constants.py, em_workflows/dm_conversion/flow.py, em_workflows/file_path.py, em_workflows/lrg_2d_rgb/flow.py, em_workflows/sem_tomo/flow.py, em_workflows/utils/neuroglancer.py, em_workflows/utils/utils.py, test/test_czi.py
Addresses
One of the todos in the code
https://github.com/niaid/image_portal_workflows/blob/main/em_workflows/file_path.py#L170
In a nutshell, asset_types are a set of possible strings. Replacing them by enums removes the possibilities of spelling errors.
* asset_type now requires Enums over strings.
=> Replace strings by Asset type constants

em_workflows/constants.py, em_workflows/czi/constants.py, em_workflows/czi/flow.py, em_workflows/lrg_2d_rgb/flow.py, em_workflows/utils/neuroglancer.py
Addresses https://github.com/niaid/image_portal_workflows/issues/273
* The changes were made in lrg2d workflow and utils.neuroglancer
=> Use workers count wherever bf2raw command is used

em_workflows/czi/flow.py, em_workflows/utils/utils.py, test/conftest.py, test/test_czi.py
* Mocks bioformats2raw (expensive command) to check if zarr has already been created
* Stores callback from workflows in temporary file so that data can be checked (example in test_czi.py)
=> Test callback structure

em_workflows/config.py, em_workflows/constants.py, em_workflows/lrg_2d_rgb/flow.py
Addresses
* Increases Java max heap size
* Increase number of dask workers (1 -> 4) and memory (32G -> 400G)
=> Update configs for java and lrg_flow.convert

.env.sample, docs/source/development.rst, em_workflows/config.py, pytest.ini, test/conftest.py
… with appropriate variables
Addresses https://github.com/niaid/image_portal_workflows/issues/287
* Removes monkeypatching `config` in pytest
* Mandates `.env` files (checked only during pytest)
=> Add pytest setup fixture to ensure .env file exists

em_workflows/czi/flow.py
Addresses https://github.com/niaid/image_portal_workflows/issues/324
* Increased tiling size for czi to zarr conversion using bf2raw
=> Increase tiling size (for czi files) in bf2raw

em_workflows/utils/neuroglancer.py
Addresses #330 
* removes    `--scale-format-string "%2$d"` from bioformats2raw in utils.ng
=> removing --scale-format-string from bioformats command

em_workflows/brt/flow.py, em_workflows/sem_tomo/flow.py, em_workflows/utils/neuroglancer.py
The zgroups aren't flattened for `brt` and `sem` flows (which was the default behavior previously). In order to compensate that, `/0` subdirectory is added to the back of the parent directory.
Closes #332
=> Fixes the removal of `scale-string-format` argument from bioformats2raw

docs/source/NeuroglancerMetadata.yaml, docs/source/metadata.yml
The dimension field is taken from the dimensions of the ZARR file which are ">1". The current supported types include what is listed in the spec. Other subsets of XYZCT are possible in the future.
Updates the neuroglancer shader parameters to match the what is produced and describes the used dimensions of the data set.
=> Update shader parameters spec to include XYC dimensions

em_workflows/brt/flow.py, em_workflows/lrg_2d_rgb/flow.py, em_workflows/sem_tomo/flow.py, test/test_brt.py, test/test_czi.py
Adds nesting for zarr file locations for single image workflows ( Closes #343 ) 
Previously, zarr directory structure was affected by `scale-format-string` argument in bf2raw command which has been removed.
Update SEM neuroglancer metadata to new format (Closes #342 )
=> Change locations for zarr image in single image workflows

em_workflows/czi/flow.py, em_workflows/lrg_2d_rgb/flow.py
Addresses (eg: #349)
* Changes call from `HedwigZarrImage.dims` to hard coded 'XY' string, as API is unable to consume 'XYC'
=> hardcode in XY for API

em_workflows/czi/flow.py
Addresses #357 
only create thumb for image name named "label image".
=> prevents thumb gen for IF images

docs/source/demo_callback.json, em_workflows/czi/flow.py, em_workflows/file_path.py
=> Return OME metadata xml file location along with ng metadata

em_workflows/czi/flow.py, em_workflows/dm_conversion/flow.py, em_workflows/lrg_2d_rgb/flow.py, em_workflows/sem_tomo/flow.py
Temporary assets are saved in `brt` workflow. This behavior is extend to rest of the workflows as well.
=> Add missing copy workdir to assets for all workflows

em_workflows/czi/flow.py
changes --tile_width / --tile_height from 4096 -> 512 ; this allows rechunk complete more quickly
=> Changing bioformats2raw chunk dims from 4K to 512

em_workflows/brt/flow.py, em_workflows/czi/flow.py, em_workflows/dm_conversion/flow.py, em_workflows/file_path.py, em_workflows/lrg_2d_rgb/flow.py, em_workflows/sem_tomo/flow.py, em_workflows/utils/neuroglancer.py, em_workflows/utils/utils.py, prefect.yaml, test/conftest.py, test/test_brt.py, test/test_utils.py
* Add `notify api running` calls as soon as the flow runs start
* czi flow run uses async/await. Wait for prefect future results before sending it to async calls
* Remove subflow for small dm conversion flow
* Revert `Completion/Failed` to original `success/error` api calls on notify-api-completion
* Refactor BRT flow: ; Increase cluster size for BRT workflow to be able to handle large number of inputs.
* post workflow tasks uses `.wait` and `.get_state` to make sure the upstream tasks have completed (not necessarily reached a terminal state).
=> Small 2D and BRT fixes

.github/workflows/main.yml, helper_scripts/hedwig_listener_qa.service
=> QA service file update

docs/source/prefect.rst, docs/source/usage.rst, em_workflows/brt/flow.py, em_workflows/czi/flow.py, em_workflows/dm_conversion/flow.py, em_workflows/lrg_2d_rgb/flow.py, em_workflows/sem_tomo/flow.py, test/test_brt.py, test/test_czi.py, test/test_lrg_2d.py, test/test_sem.py, test/test_utils.py
- Fixing up tests, improving docs, using `on_crash` hook to do cleanup.
=> adds `on_crash` hook and updates doc on main.

em_workflows/test_runner/flow.py
previously test runner was using `dev` branch to run tests. Run in `main` instead.
=> default to testing in main branch

requirements.txt
prefect changed how they package their dask setup
=> new dask install method

requirements.txt
Address delock condition when using dask.array with in prefect clusters.
Addresses #478
=> Update pytools to 3.3.0

.env.sample, .github/workflows/main.yml, docs/source/development.rst, em_workflows/brt/flow.py, em_workflows/config.py, em_workflows/dm_conversion/flow.py
=> Add GraphicMagic as a configurable executable

em_workflows/dm_conversion/flow.py, em_workflows/file_path.py, test/test_file_path.py
The prior implemenation would wait until the process had completed before producing any outputs to the file or to the log. This improvement reports the standard output and error as each line is being produced.
=> Log and write subprocess output as produced.

docs/source/api/dm_conversion/flow.rst, em_workflows/dm_conversion/flow.py, em_workflows/utils/utils.py
Refactor the dm_convert pipeline.
Create a function to convert mrc to tiff files with newstack
Replace dm->jpeg step with newstack function.
Move separate "conditional" tasks into one function.
=> DM convert refactor
