niaid/image_portal_workflows

em_workflows/brt/flow.py
em_workflows/dm_conversion/flow.py
em_workflows/sem_tomo/flow.py
em_workflows/shell_task_echo.py
em_workflows/utils/neuroglancer.py
em_workflows/utils/utils.py
test/test_dm.py

Still needs more work - but now logs in a more useful way.

Logging improvments

---

em_workflows/brt/flow.py
em_workflows/sem_tomo/flow.py
em_workflows/utils/utils.py

various changes related to movie gen

Add corr mrc fibsem

---

em_workflows/brt/flow.py
em_workflows/file_path.py

recon movie should have been using z dimension from the _rec mrc file

Fix recon movie

---

em_workflows/brt/flow.py
em_workflows/utils/utils.py

Any single success in a batch should define a top level success.

Mod final state

---

helper_scripts/hedwig_reg_listen.sh

allows mult prefect hosts to run on single machine

export PREFECT__SERVER__HOST

---

em_workflows/brt/flow.py
em_workflows/dm_conversion/flow.py
em_workflows/sem_tomo/flow.py
em_workflows/templates/cryo_brt.adoc
em_workflows/templates/plastic_brt.adoc
em_workflows/utils/neuroglancer.py
em_workflows/utils/utils.py
test/test_brt.py
test/test_dm.py
test/test_sem.py

addresses a number of perf issues, including adoc config. 
Also adds no_api mode.

Optimize vol to pyr

---

docs/development.rst

Minimal changes to `development.rst` just try go through GH PR cycle.
No associated issue.

Made some simple document changes to test if I can push.

---

test/test_dm.py

Replaces hard-coded paths to be more platform independent.

Determine executable paths dynamically

---

docs/development.rst
em_workflows/config.py
helper_scripts/generate_venv.sh
requirements.txt
test/copy_test_data.sh
test/test_brt.py
test/test_callback.py
test/test_dm.py
test/test_sem.py

Also updated/added documentation and changed tomojs_pytools dependency to v1.3.6.

Changed Config class and tests to be more platform-independent

---

em_workflows/file_path.py
em_workflows/sem_tomo/flow.py
requirements.txt

adds docstring to Fibsem, echos cmd run to top of log file.

Adds natsort to deal with input fnames

---

em_workflows/brt/flow.py
em_workflows/utils/neuroglancer.py

also remove defunct gen_mrc2nifti_cmd()

Update brt pipeline docs

---

docs/source/neuroglancer.rst
docs/source/utils.rst
em_workflows/file_path.py
em_workflows/utils/neuroglancer.py
em_workflows/utils/utils.py

Added docstrings and improved Sphinx docs - mostly FilePath

---

.github/workflows/main.yml
docs/requirements.txt
docs/source/brt_flow.rst
em_workflows/brt/flow.py
em_workflows/file_path.py
em_workflows/utils/utils.py
test/test_callback.py

- Included parent requirements.txt in docs/requirements.txt so GH Action should now build docs.
- Cleaned up warnings in brt.flow and made docstrings more readable.
- Commented out some unused functions

Added Prefect to requirements.txt and improved docstrings

---

em_workflows/config.py
em_workflows/dm_conversion/flow.py
em_workflows/file_path.py
em_workflows/utils/utils.py
test/conftest.py
test/input_files/P6_J128_selected_11_classes.jpeg
test/test_brt.py
test/test_dm.py
test/test_sem.py
test/test_utils.py

Added some simple Utils tests, including one with `__wrapped__` check. Consolidated common test fixtures into `conftest.py`. Cleaned up some code, including adding dimension constants in config.py (e.g. LARGE_2D) and commenting out unused `utils.init_log()` function.

Added utils tests; cleaned up test dir

---

docs/source/utils.rst
em_workflows/utils/utils.py
test/test_callback.py
test/test_utils.py

Added additional tests of utils.py

---

em_workflows/sem_tomo/flow.py

closes https://github.com/niaid/image_portal_workflows/issues/187

PERF: Combine newstack commands which apply transforms.

---

.coveragerc
.github/workflows/main.yml
README.rst
docs/source/sem_flow.rst
test/test_utils.py

On GH Pull Request, basics tests will run and a test coverage badge created and displayed on the main README.

Tests and Coverage upon GH Actions

---

.github/workflows/main.yml
test/test_dm.py
test/test_utils.py

One test_utils.py test is unexpectedly failing, but at least the programs are found.

Fixed IMOD path issues and skipped bad dm tests

---

docs/source/em_workflows.rst
docs/source/neuroglancer.rst
docs/source/shell_task_echo.rst
em_workflows/utils/neuroglancer.py

Includes small change to docstring in `neuroglancer.py`

Cleaned up errors in Sphinx docs build

---

docs/source/development.rst

Added some description for pre-commit and bioformats2raw.

Updated the Development page of the docs.

---

.coveragerc
coverage.svg
em_workflows/file_path.py
em_workflows/utils/utils.py
test/test_utils.py

This was rebased off of 99a63a1

Increasing test coverage; commented out dead code

---

docs/source/hpc.rst
em_workflows/config.py
env_dev.yml
env_prod.yml
env_qa.yml
helper_scripts/generate_venv.sh
helper_scripts/hedwig_listener_dev.service
helper_scripts/hedwig_listener_prod.service
helper_scripts/hedwig_listener_qa.service
helper_scripts/hedwig_reg_listen.sh

Adding information and mods related to service account set ups

Hpc install mods

---

.flake8
em_workflows/config.py
setup.py

https://docs.python.org/3/distutils/setupscript.html#installing-package-data, fixes #250

tells setup to install templates, fixes #250

---

docs/source/hpc.rst
em_workflows/config.py

SEM jobs were timing out - closes https://github.com/niaid/image_portal_workflows/issues/257

Bump slurm walltime

---

.github/workflows/main.yml
test/test_lrg_2d.py
test/test_utils.py

Added installation of `bioformats2raw` to GH push action which also required Java. Added a test to verify it works.

Added bioformats2raw to GH build and added tests.

---

test/test_brt.py

Just removed the test code for now. No changes to `utils.py` yet.

Removed "shortcut" code from BRT test.

---

docs/source/batch_macro_image.sh

This demo script used tools from bioformats include showinf, and bfconvert.

Script to extract a czi "macro images" to a thumbnail

---

em_workflows/lrg_2d_rgb/flow.py

Addresses - https://github.com/niaid/image_portal_workflows/issues/292
Depends on - https://github.com/niaid/image_portal_workflows/tree/czi_to_zarr_wf

Refactor large 2d flow

---

helper_scripts/hedwig_reg_listen.sh

Register new czi workflow

---

requirements.txt

bumps our requirements to pytools version v3.0b01

bumps pytools version - new SITK goodies - closes #312

---

em_workflows/dm_conversion/flow.py
test/test_czi.py
test/test_dm.py
test/test_lrg_2d.py
test/test_utils.py

* Moving tests to appropriate locations
* Increasing the coverage

Polish tests; Refactor and move tests

---

helper_scripts/hedwig_reg_listen.sh

Closes https://github.com/niaid/image_portal_workflows/issues/307
set indent to tabs throughout

fix up mixed tabs / spaces

---

em_workflows/utils/neuroglancer.py
em_workflows/utils/utils.py

Addresses #302
General cleanup of commented out code.

killing off dead / commented out code - closes #302

---

requirements.txt

Bumps to pytools 3.0b02

---

requirements.txt

use pytools wheel

---

em_workflows/czi/flow.py

Aligned the text of the image, closes #351

Rotate label image 90 clock wise

---

em_workflows/czi/flow.py
em_workflows/file_path.py

Add omeXml: null in fileMetadata of all results

---

em_workflows/dm_conversion/constants.py
em_workflows/dm_conversion/flow.py
test/test_dm.py

Refactor dm workflow

---

em_workflows/config.py
em_workflows/czi/flow.py

- Add default and high slurm cluster specs

Add different cluster configs

---

em_workflows/utils/neuroglancer.py
requirements.txt

Allow in memory zarr rechunk

---

em_workflows/brt/flow.py
em_workflows/czi/flow.py
em_workflows/dm_conversion/flow.py
em_workflows/file_path.py
em_workflows/lrg_2d_rgb/flow.py
em_workflows/sem_tomo/flow.py
em_workflows/utils/utils.py
requirements-dev.txt
requirements.txt
test/test_brt.py
test/test_czi.py
test/test_sem.py
test/test_utils.py

Fixes issues with dm test, large 2d test, brt, cleanup, adds workflow name

---

em_workflows/config.py
em_workflows/constants.py

closes #391 
reduces runtime on #391 to <5 mins.

Changes benchmarked inc speed ~1.5hrs -> 5mins

---

em_workflows/brt/flow.py
em_workflows/config.py
em_workflows/czi/flow.py
em_workflows/dm_conversion/flow.py
em_workflows/lrg_2d_rgb/flow.py
em_workflows/sem_tomo/flow.py
em_workflows/utils/utils.py
test/test_lrg_2d.py
test/test_utils.py

Move `copy_workdirs` and `cleanup` tasks as hooks (completion or failure).

Refactor post workflow tasks

---

test/conftest.py

Fix mock rechunk

---

em_workflows/brt/flow.py
em_workflows/utils/neuroglancer.py

Add missing zarr asset copy

---

docs/source/usage.rst

adding prod UUIDs to usage.rst

---

requirements.txt

bump to prefect 2.18.1 to test updated FE

bump n2 version

---

em_workflows/config.py
em_workflows/sem_tomo/config.py
em_workflows/utils/utils.py
setup.py

closes https://github.com/niaid/image_portal_workflows/issues/480

tag brt runs, update imod version

---

em_workflows/dm_conversion/config.py

Use imod_root for dm2mrc path

---

em_workflows/brt/flow.py
em_workflows/config.py
em_workflows/czi/flow.py
em_workflows/dm_conversion/flow.py
em_workflows/lrg_2d_rgb/flow.py
em_workflows/sem_tomo/flow.py
em_workflows/utils/utils.py

- **Remove traces of local_storage**
- **Add back dm config task runner**

Remove local storage occurrence
